CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id varchar(128) NOT NULL,
    amount bigint NOT NULL CHECK (amount >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    status varchar(32) NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE public.order_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id),
    operation varchar(16) NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE FUNCTION public.audit_order_insert() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO public.order_audit(order_id, operation)
    VALUES (NEW.id, 'INSERT');
    RETURN NEW;
END;
$$;

CREATE TRIGGER orders_after_insert
AFTER INSERT ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.audit_order_insert();
