/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analysis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listAnalysisRuns"];
        put?: never;
        post: operations["startAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getAnalysisRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/events": {
        parameters: {
            query?: never;
            header?: {
                /** @description Last received SSE id; events must have an id for automatic browser replay */
                "Last-Event-ID"?: string;
            };
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** @description SSE messages may be unnamed or have event names equal to their data.type. Clients handle all event names, preserve Last-Event-ID on reconnect, and deduplicate by sequenceNumber. */
        get: operations["streamAnalysisEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/canvas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getCanvas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/layout": {
        parameters: {
            query: {
                view: components["schemas"]["CanvasView"];
            };
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getLayout"];
        put: operations["saveLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get: operations["getSemanticNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/nodes/{nodeId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get: operations["getNodeEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/edges/{edgeId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        get: operations["getEdgeEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/nodes/{nodeId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/semantic-diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["getSemanticDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/analyzer-plan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getAnalyzerPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/quarantined-facts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getQuarantinedFacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/unresolved-symbols": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getUnresolvedSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get: operations["getRuntimeEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{analysisRunId}/runtime/traces": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Developer-only import into a completed analysis. Accepts uncompressed OTLP JSON up to 1 MiB and 500 spans; duplicate IDs are idempotent only with identical immutable data. */
        post: operations["ingestRuntimeTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RuntimeSpan: {
            /** Format: uuid */
            id: string;
            traceId: string;
            spanId: string;
            parentSpanId: string | null;
            name: string;
            kind: number;
            /** @description Unsigned Unix nanoseconds; preserve as a string */
            startNanos: string;
            endNanos: string;
            attributes: {
                [key: string]: unknown;
            };
            resourceAttributes: {
                [key: string]: unknown;
            };
            scope: {
                [key: string]: unknown;
            };
            status: {
                [key: string]: unknown;
            };
            events: {
                [key: string]: unknown;
            }[];
            links: {
                [key: string]: unknown;
            }[];
            /** Format: uuid */
            matchedNodeId: string | null;
            /** @enum {string} */
            matchStatus: "MATCHED_STABLE_KEY" | "MATCHED_SYMBOL" | "UNRESOLVED" | "AMBIGUOUS";
            createdAt: string;
        };
        RuntimeSnapshot: {
            /** Format: uuid */
            analysisRunId: string;
            spans: components["schemas"]["RuntimeSpan"][];
            summary: {
                totalSpans: number;
                traceCount: number;
                matchedSpans: number;
                unresolvedSpans: number;
                observedNodes: number;
                notObservedNodes: number;
                /** @enum {string} */
                coverageScope: "UPLOADED_SPANS_ONLY";
                /** @enum {boolean} */
                wholeApplicationCoverageKnown: false;
                /** @enum {string} */
                notObservedMeaning: "NOT_OBSERVED_IN_UPLOADED_TRACES";
            };
            observedPaths: {
                /** Format: uuid */
                sourceNodeId: string;
                /** Format: uuid */
                targetNodeId: string;
            }[];
            pathsTruncated: boolean;
            offset: number;
            limit: number;
            hasMore: boolean;
        };
        RuntimeIngestion: {
            /** @enum {string} */
            status: "INGESTED";
            acceptedSpans: number;
            duplicateSpans: number;
            matchedSpans: number;
            unresolvedSpans: number;
            /** @enum {string} */
            coverageScope: "UPLOADED_SPANS_ONLY";
        };
        ProjectInput: {
            name: string;
            description: string;
            repositoryPath: string;
        };
        Project: components["schemas"]["ProjectInput"] & {
            id: string;
            createdAt: string;
        };
        RepositoryInput: {
            url: string;
            branch: string;
        };
        Repository: components["schemas"]["RepositoryInput"] & {
            id: string;
        };
        AnalysisInput: {
            /** Format: uuid */
            baselineRunId?: string;
            ref?: string;
        };
        AnalysisRun: {
            id: string;
            projectId: string;
            status: string;
            revision: string | null;
            createdAt: string;
            finishedAt: string | null;
            progress: number;
            currentStage: string | null;
        };
        AnalysisEvent: {
            sequenceNumber: number;
            type: string;
            message: string;
            progress: number;
            createdAt: string;
        };
        /** @enum {string} */
        CanvasView: "BUSINESS" | "DEVELOPER" | "DATA_OWNERSHIP" | "SECURITY" | "DATA_PIPELINE" | "CONFIDENCE";
        SemanticNode: {
            id: string;
            stableKey: string;
            kind: string;
            label: string;
            subtitle: string | null;
            confidence: number;
            supportLevel: string;
            evidenceCount: number;
            reviewStatus: string;
            badges: string[];
            properties: {
                [key: string]: unknown;
            };
        };
        SemanticNodeDetail: components["schemas"]["SemanticNode"] & {
            facts?: unknown[];
            scenarios?: unknown[];
            assertions?: unknown[];
            enrichments?: unknown[];
            reviews?: unknown[];
        };
        SemanticEdge: {
            id: string;
            source: string;
            target: string;
            kind: string;
            label: string | null;
            confidence: number;
            evidenceCount: number;
        };
        CanvasProjection: {
            nodes: components["schemas"]["SemanticNode"][];
            edges: components["schemas"]["SemanticEdge"][];
            truncated: boolean;
            totalNodes: number;
        };
        CanvasLayout: {
            /** @description Pinned node stable keys; must be a subset of positions. Omitted on write means no pinned nodes. */
            pinnedStableKeys?: string[];
            positions: {
                [key: string]: {
                    x: number;
                    y: number;
                };
            };
            viewport: {
                x: number;
                y: number;
                zoom: number;
            };
        };
        Evidence: {
            id: string;
            filePath: string;
            startLine: number;
            endLine: number;
            snippet: string | null;
            snippetHash: string | null;
            analyzerId: string;
            analyzerVersion: string | null;
            imageDigest: string | null;
            origin: string;
            verified: boolean;
            /** @description False when retention has removed the source snippet; evidence metadata remains available. */
            sourceAvailable?: boolean;
        };
        ReviewInput: {
            /** @enum {string} */
            decision: "CONFIRMED" | "REJECTED" | "EDITED" | "MERGED" | "MARKED_TECHNICAL" | "NEEDS_REVIEW";
            comment: string;
            editedTitle: string;
            editedDescription: string;
            /** Format: uuid */
            mergeTargetId?: string;
        };
        SemanticChange: {
            id: string;
            changeType: string;
            subjectStableKey: string;
            impactType: string;
            before: unknown;
            after: unknown;
            beforeEvidenceIds: string[];
            afterEvidenceIds: string[];
            confidence: number;
        };
        SettingsInput: {
            /** @enum {string} */
            aiMode: "DISABLED" | "LOCAL_PROVIDER" | "REMOTE_PROVIDER";
            remoteAllowed: boolean;
            retentionDays: number;
        };
        Settings: {
            aiMode: string;
            remoteAllowed: boolean;
            authMode: string;
            retentionDays: number;
            capabilities: string[] | {
                [key: string]: unknown;
            };
        };
        InspectionData: {
            [key: string]: unknown;
        } | unknown[];
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
            errorCode?: string;
            correlationId?: string;
            fieldErrors?: unknown;
        };
    };
    responses: {
        /** @description Structured diagnostic data; fields vary by analyzer capability */
        Inspection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InspectionData"];
            };
        };
        /** @description RFC 7807 error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        RunId: string;
        NodeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects visible to the current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created project */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project archived; immutable history and audit are preserved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    addRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryInput"];
            };
        };
        responses: {
            /** @description Attached repository */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
        };
    };
    listAnalysisRuns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"][];
                };
            };
        };
    };
    startAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisInput"];
            };
        };
        responses: {
            /** @description Queued analysis run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
        };
    };
    getAnalysisRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state; progress is a percentage from 0 to 100 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
        };
    };
    cancelAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted; client refreshes run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cancellation accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamAnalysisEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Last received SSE id; events must have an id for automatic browser replay */
                "Last-Event-ID"?: string;
            };
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server sent events, data JSON matches AnalysisEvent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getCanvas: {
        parameters: {
            query?: {
                view?: components["schemas"]["CanvasView"];
                depth?: number;
                levelOfDetail?: number;
                onlyChanged?: boolean;
                minConfidence?: number;
                rootNodeId?: string;
                search?: string;
            };
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded projection with no source snippets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasProjection"];
                };
            };
        };
    };
    getLayout: {
        parameters: {
            query: {
                view: components["schemas"]["CanvasView"];
            };
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable key positions and viewport; new layouts return empty positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasLayout"];
                };
            };
            /** @description No saved layout */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveLayout: {
        parameters: {
            query: {
                view: components["schemas"]["CanvasView"];
            };
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasLayout"];
            };
        };
        responses: {
            /** @description Layout saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Layout saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSemanticNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node and separate interpretation layers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticNodeDetail"];
                };
            };
        };
    };
    getNodeEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence with exact source locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
        };
    };
    getEdgeEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence explaining the selected relationship */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
        };
    };
    reviewNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Review recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Review recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReviewQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes awaiting review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticNode"][];
                };
            };
        };
    };
    getSemanticDiff: {
        parameters: {
            query: {
                fromAnalysisRun: string;
                toAnalysisRun: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic semantic changes between two runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticChange"][];
                };
            };
        };
    };
    getCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inspection"];
        };
    };
    getDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inspection"];
        };
    };
    getAnalyzerPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inspection"];
        };
    };
    getQuarantinedFacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inspection"];
        };
    };
    getUnresolvedSymbols: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inspection"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective platform settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description Settings saved; client refreshes effective settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Settings saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRuntimeEvidence: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated uploaded spans and bounded observed paths; not whole-application coverage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSnapshot"];
                };
            };
        };
    };
    ingestRuntimeTraces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisRunId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    resourceSpans: {
                        [key: string]: unknown;
                    }[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Imported observations; static facts are unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeIngestion"];
                };
            };
            /** @description Invalid OTLP JSON */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Developer access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Analysis not complete or immutable span conflicts */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Body or span count exceeds the import limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Compressed payloads are not supported */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-analysis span quota exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
