const en = {
  title: 'Runtime evidence',
  explanation:
    'Observations describe uploaded traces only. A node without an observation may still execute; whole-application coverage is unknown.',
  file: 'OTLP JSON file',
  upload: 'Import traces',
  uploadHelp:
    'Uncompressed OTLP JSON, up to 1 MiB and 500 spans per upload. Requires project developer access.',
  wait: 'Import becomes available after the static analysis completes.',
  invalid: 'Choose a valid OTLP JSON object with resourceSpans.',
  tooLarge: 'The trace file exceeds 1 MiB.',
  empty: 'No runtime observations yet',
  emptyHelp:
    'Import an OTLP JSON export with semantic.stable_key or a qualified code.function.name to match spans to the analyzed revision.',
  total: 'Spans',
  traces: 'Traces',
  observed: 'Observed nodes',
  unobserved: 'Nodes not observed in these traces',
  matched: 'Matched spans',
  unresolved: 'Unresolved spans',
  accepted: 'Imported spans',
  duplicates: 'Already imported',
  paths: 'Observed parent–child paths',
  pathsLimited: 'Only the first 500 observed paths are shown.',
  span: 'Span',
  match: 'Match',
  duration: 'Duration (ms)',
  details: 'Span details',
  source: 'Source evidence',
  parent: 'Parent span',
  noParent: 'Root span',
  noMatch: 'No unique source match',
  MATCHED_STABLE_KEY: 'Exact stable key',
  MATCHED_SYMBOL: 'Qualified symbol',
  UNRESOLVED: 'Unresolved',
  AMBIGUOUS: 'Ambiguous',
  kind0: 'Unspecified',
  kind1: 'Internal',
  kind2: 'Server',
  kind3: 'Client',
  kind4: 'Producer',
  kind5: 'Consumer',
  from: 'Source node',
  to: 'Target node',
  page: 'Page',
};
const ru: Record<keyof typeof en, string> = {
  title: 'Runtime-доказательства',
  explanation:
    'Наблюдения относятся только к загруженным трассам. Узел без наблюдения всё ещё может выполняться; покрытие всего приложения неизвестно.',
  file: 'Файл OTLP JSON',
  upload: 'Импортировать трассы',
  uploadHelp:
    'Несжатый OTLP JSON: до 1 МиБ и 500 spans за одну загрузку. Нужны права разработчика проекта.',
  wait: 'Импорт станет доступен после завершения статического анализа.',
  invalid: 'Выберите корректный объект OTLP JSON с resourceSpans.',
  tooLarge: 'Размер файла трасс превышает 1 МиБ.',
  empty: 'Runtime-наблюдений пока нет',
  emptyHelp:
    'Импортируйте OTLP JSON с semantic.stable_key или полным code.function.name для сопоставления с проанализированной ревизией.',
  total: 'Spans',
  traces: 'Трассы',
  observed: 'Наблюдавшиеся узлы',
  unobserved: 'Узлы без наблюдений в этих трассах',
  matched: 'Сопоставленные spans',
  unresolved: 'Неразрешённые spans',
  accepted: 'Импортировано spans',
  duplicates: 'Уже импортированы',
  paths: 'Наблюдавшиеся связи родитель–потомок',
  pathsLimited: 'Показаны только первые 500 наблюдавшихся связей.',
  span: 'Span',
  match: 'Сопоставление',
  duration: 'Длительность (мс)',
  details: 'Подробности span',
  source: 'Исходные доказательства',
  parent: 'Родительский span',
  noParent: 'Корневой span',
  noMatch: 'Однозначная связь с исходником не найдена',
  MATCHED_STABLE_KEY: 'Точный стабильный ключ',
  MATCHED_SYMBOL: 'Полное имя символа',
  UNRESOLVED: 'Не разрешено',
  AMBIGUOUS: 'Неоднозначно',
  kind0: 'Не задан',
  kind1: 'Внутренний',
  kind2: 'Сервер',
  kind3: 'Клиент',
  kind4: 'Отправитель',
  kind5: 'Получатель',
  from: 'Исходный узел',
  to: 'Целевой узел',
  page: 'Страница',
};
export const runtimeText = { en, ru };
