import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFile, mkdir, writeFile, lstat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Inventory metadata only. Repository text is never executed or sent to a service.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ownOutputs = new Set(['docs/PROJECT_INDEX.md']);
const paths = execFileSync('git', ['-c', `safe.directory=${root.replaceAll('\\', '/')}`,
  'ls-files', '--cached', '--others', '--exclude-standard', '-z'], { cwd: root, encoding: 'utf8' });
const candidates = [...new Set(paths.split('\0').filter(Boolean))].sort();
const files = [];
function area(file) {
  if (file.startsWith('backend/platform/src/')) {
    const feature = file.match(/\/io\/semanticmap\/platform\/([^/]+)\//)?.[1];
    return feature ? `backend/${feature}` : 'backend/bootstrap-and-schema';
  }
  if (file.startsWith('analyzers/')) return file.split('/').slice(0, 2).join('/');
  if (file.startsWith('frontend/src/features/')) return file.split('/').slice(0, 4).join('/');
  if (file.startsWith('frontend/')) return file.split('/').length > 2 ? `frontend/${file.split('/')[1]}` : 'frontend/configuration';
  return file.includes('/') ? file.split('/')[0] : 'build-and-project';
}
function role(file) {
  if (/(?:^|\/)(?:tests?|e2e|fixtures|examples)(?:\/|\.)/.test(file) || /(?:Test|IT|Benchmark)\.java$|\.(?:test|spec)\.[cm]?[jt]sx?$/.test(file)) return 'test/fixture';
  if (/\.md$/.test(file)) return 'documentation';
  if (/\/migration\//.test(file)) return 'migration';
  if (/\.schema\.json$|api-contract\.yaml$|generated\.ts$/.test(file)) return 'contract';
  if (/\.(?:java|[cm]?[jt]sx?|py|css)$/.test(file)) return 'source';
  return 'configuration/tooling';
}
for (const file of candidates) {
  if (ownOutputs.has(file) || /(?:^|\/)(?:node_modules|\.pnpm-store|target|dist|output|__pycache__)(?:\/|$)/.test(file)) continue;
  const absolute = path.resolve(root, file);
  if (!absolute.startsWith(root + path.sep)) throw new Error(`Path outside workspace: ${file}`);
  let stat;
  try { stat = await lstat(absolute); } catch (error) { if (error.code === 'ENOENT') continue; throw error; }
  if (!stat.isFile() || stat.isSymbolicLink()) continue;
  const bytes = await readFile(absolute);
  const binary = bytes.subarray(0, 8192).includes(0);
  const text = binary ? null : bytes.toString('utf8');
  files.push({ path: file, area: area(file), role: role(file), bytes: bytes.length,
    lines: text === null ? null : text ? text.split('\n').length - Number(text.endsWith('\n')) : 0,
    sha256: createHash('sha256').update(bytes).digest('hex') });
}
const areas = [...new Set(files.map(file => file.area))].sort();
const inventory = { schemaVersion: 1, description: 'Local Git-visible regular files; excludes generated inventory and ignored artifacts. Metadata is an index, not verification of behavior.', files };
await mkdir(path.join(root, 'output'), { recursive: true });
await writeFile(path.join(root, 'output/project-index.json'), JSON.stringify(inventory, null, 2) + '\n');
const lines = ['# Project Index', '',
  'Generated by `node scripts/index-project.mjs`. Includes tracked and non-ignored new files;',
  'excludes dependencies, build outputs, symlinks and this generated document.',
  'Machine-readable sizes, line counts and SHA-256 hashes: `output/project-index.json`.',
  'This is a navigation index. Requirement status and executed checks are maintained in',
  '[PROJECT_AUDIT.md](PROJECT_AUDIT.md) and [VERIFICATION.md](VERIFICATION.md).', '',
  `Files: **${files.length}**. Areas: **${areas.length}**.`, '',
  '| Area | Files | Source | Tests/fixtures |', '| --- | ---: | ---: | ---: |'];
for (const item of areas) {
  const members = files.filter(file => file.area === item);
  lines.push(`| ${item} | ${members.length} | ${members.filter(file => file.role === 'source').length} | ${members.filter(file => file.role === 'test/fixture').length} |`);
}
for (const item of areas) {
  lines.push('', `## ${item}`, '');
  for (const file of files.filter(file => file.area === item)) {
    const link = '../' + file.path.split('/').map(encodeURIComponent).join('/');
    lines.push(`- [${file.path}](${link}) — ${file.role}${file.lines === null ? '' : `, ${file.lines} lines`}`);
  }
}
await writeFile(path.join(root, 'docs/PROJECT_INDEX.md'), lines.join('\n') + '\n');
console.log(`Indexed ${files.length} files in ${areas.length} areas. See docs/PROJECT_INDEX.md and output/project-index.json.`);
